apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  username: root
  password: {{ randAlphaNum 16 | quote }}
